import { Permission, permission, userGroup, UserGroup } from "../models";

export const COMPANY_ADMIN_PERMISSION = [permission.COMPANY_MODULE_READ, permission.COMPANY_MODULE_WRITE];

export const COMPANY_READONLY_PERMISSION = [permission.COMPANY_MODULE_READ];

export const CLIENT_ADMIN_PERMISSION = [permission.CLIENT_MODULE_READ, permission.CLIENT_MODULE_WRITE];

export const CLIENT_READONLY_PERMISSION = [permission.DISPATCH_MODULE_READ];

export const DISPATCH_ADMIN_PERMISSION = [permission.DISPATCH_MODULE_READ, permission.DISPATCH_MODULE_WRITE];

export const DISPATCH_READONLY_PERMISSION = [permission.CLIENT_MODULE_READ];

export const LOAD_ADMIN_PERMISSION = [permission.LOAD_MODULE_READ, permission.LOAD_MODULE_WRITE];

export const LOAD_READONLY_PERMISSION = [permission.LOAD_MODULE_READ];

export const EMPLOYEE_ADMIN_PERMISSION = [permission.EMPLOYEE_MODULE_READ, permission.EMPLOYEE_MODULE_WRITE];

export const EMPLOYEE_READONLY_PERMISSION = [permission.EMPLOYEE_MODULE_READ];

export const INVOICE_ADMIN_PERMISSION = [permission.INVOICE_MODULE_READ, permission.INVOICE_MODULE_WRITE];

export const INVOICE_READONLY_PERMISSION = [permission.INVOICE_MODULE_READ];

export const USER_READONLY_PERMISSION = [permission.USER_MODULE_READ];

export const USER_ADMIN_PERMISSION = [permission.USER_MODULE_READ, permission.USER_MODULE_WRITE];

export const TRUCK_TRAILER_READONLY_PERMISSION = [permission.VEHICLE_TRUCK_TRAILER_MODULE_READ];

export const TRUCK_TRAILER_ADMIN_PERMISSION = [
  permission.VEHICLE_TRUCK_TRAILER_MODULE_READ,
  permission.VEHICLE_TRUCK_TRAILER_MODULE_WRITE,
];

// Owner permission
export const OWNER_PERMISSIONS = [
  ...COMPANY_ADMIN_PERMISSION,
  ...CLIENT_ADMIN_PERMISSION,
  ...DISPATCH_ADMIN_PERMISSION,
  ...LOAD_ADMIN_PERMISSION,
  ...EMPLOYEE_ADMIN_PERMISSION,
  ...INVOICE_ADMIN_PERMISSION,
  ...USER_READONLY_PERMISSION,
  ...TRUCK_TRAILER_ADMIN_PERMISSION,
  permission.COMPANY_USER_WRITE,
];

// Admin permission
export const ADMIN_PERMISSIONS = [...OWNER_PERMISSIONS, ...USER_ADMIN_PERMISSION];

// Load permissions
export const LOAD_ADMIN_PERMISSIONS = [
  ...INVOICE_ADMIN_PERMISSION,
  ...LOAD_ADMIN_PERMISSION,
  ...CLIENT_ADMIN_PERMISSION,
  ...COMPANY_READONLY_PERMISSION,
];
export const LOAD_READONLY_PERMISSIONS = [
  ...INVOICE_READONLY_PERMISSION,
  ...LOAD_READONLY_PERMISSION,
  ...CLIENT_READONLY_PERMISSION,
  ...COMPANY_READONLY_PERMISSION,
  ...EMPLOYEE_READONLY_PERMISSION,
];

// Dispatcher permissions
export const DISPATCHER_ADMIN_PERMISSIONS = [
  ...TRUCK_TRAILER_ADMIN_PERMISSION,
  ...LOAD_ADMIN_PERMISSIONS,
  permission.COMPANY_USER_WRITE,
  ...COMPANY_READONLY_PERMISSION,
  ...EMPLOYEE_READONLY_PERMISSION,
];

export const DISPATCHER_READONLY_PERMISSIONS = [
  ...TRUCK_TRAILER_READONLY_PERMISSION,
  ...LOAD_READONLY_PERMISSIONS,
  ...COMPANY_READONLY_PERMISSION,
];

// Groups permissions
export const groupsPermissions: Readonly<Record<UserGroup, Permission[]>> = {
  [userGroup.ACCOUTING_ADMIN]: [...INVOICE_ADMIN_PERMISSION],
  [userGroup.ACCOUTING_READONLY]: [...INVOICE_READONLY_PERMISSION],
  [userGroup.ADMIN]: [...ADMIN_PERMISSIONS],
  [userGroup.DISPATCHER_ADMIN]: [...DISPATCHER_ADMIN_PERMISSIONS],
  [userGroup.DISPATCHER_READONLY]: [...LOAD_READONLY_PERMISSIONS, ...COMPANY_READONLY_PERMISSION],
  [userGroup.DRIVER_READONLY]: [...LOAD_READONLY_PERMISSION, ...COMPANY_READONLY_PERMISSION],
  [userGroup.OWNER]: [...OWNER_PERMISSIONS],
};
