/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateCompanyPayloadDtoAddressGeolocation { 
    /**
     * 45.815
     */
    latitude: number;
    /**
     * 15.9819
     */
    longitude: number;
}

