/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateDispatchResponseDto { 
    /**
     * cad37377-efb3-40dg-a1e2-534c2e3f84f4
     */
    employeeId: string;
    /**
     * cad37377-efb3-40dg-a1e2-534c2e3f84f4
     */
    trailerId: string;
    /**
     * cad37377-efb3-40dg-a1e2-534c2e3f84f4
     */
    truckId: string;
    created_at?: any | null;
    id: string;
    updated_at?: any | null;
}

