/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateCompanyPayloadDtoInvoiceSettings } from './createCompanyPayloadDtoInvoiceSettings';
import { CreateCompanyPayloadDtoAddress } from './createCompanyPayloadDtoAddress';


export interface CreateCompanyPayloadDto { 
    address: CreateCompanyPayloadDtoAddress;
    invoice_settings?: CreateCompanyPayloadDtoInvoiceSettings | null;
    /**
     * Deki Transport d.o.o.
     */
    name: string;
    /**
     * 12345678901
     */
    oib: string;
}

