/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateCompanyPayloadDtoInvoiceSettingsVatDescriptionInner } from './createCompanyPayloadDtoInvoiceSettingsVatDescriptionInner';


export interface CreateCompanyPayloadDtoInvoiceSettings { 
    invoice_number_separator?: CreateCompanyPayloadDtoInvoiceSettingsInvoiceNumberSeparatorEnum;
    vat_description?: Array<CreateCompanyPayloadDtoInvoiceSettingsVatDescriptionInner>;
    vat_percentage?: number | null;
}
export enum CreateCompanyPayloadDtoInvoiceSettingsInvoiceNumberSeparatorEnum {
    Minus = '-',
    Period = '.',
    Slash = '/'
};



