/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateCompanyPayloadDtoAddressGeolocation } from './createCompanyPayloadDtoAddressGeolocation';


export interface CreateCompanyPayloadDtoAddress { 
    /**
     * Zagreb
     */
    city: string;
    /**
     * Croatia
     */
    country: CreateCompanyPayloadDtoAddressCountryEnum;
    geolocation?: CreateCompanyPayloadDtoAddressGeolocation | null;
    /**
     * 46a
     */
    house_number: string;
    /**
     * 524675
     */
    postal_code: string;
    /**
     * Dobra ulica
     */
    street: string;
}
export enum CreateCompanyPayloadDtoAddressCountryEnum {
    Albania = 'Albania',
    Austria = 'Austria',
    Belgium = 'Belgium',
    Bosnia_and_Herzegovina = 'Bosnia and Herzegovina',
    Bulgaria = 'Bulgaria',
    Croatia = 'Croatia',
    Czech_Republic = 'Czech Republic',
    Denmark = 'Denmark',
    Finland = 'Finland',
    France = 'France',
    Germany = 'Germany',
    Greece = 'Greece',
    Hungary = 'Hungary',
    Ireland = 'Ireland',
    Italy = 'Italy',
    Latvia = 'Latvia',
    Lithuania = 'Lithuania',
    Netherlands = 'Netherlands',
    North_Macedonia = 'North Macedonia',
    Norway = 'Norway',
    Poland = 'Poland',
    Romania = 'Romania',
    Russia = 'Russia',
    Serbia = 'Serbia',
    Slovakia = 'Slovakia',
    Slovenia = 'Slovenia',
    Spain = 'Spain',
    Sweden = 'Sweden',
    Switzerland = 'Switzerland',
    Turkey = 'Turkey',
    Ukraine = 'Ukraine',
    United_Kingdom = 'United Kingdom'
};



