/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateUserResponseDto { 
    /**
     * Assign unique email address
     */
    email: string;
    /**
     * Assign the user group or groupes you want the new user to have.
     */
    groups: Array<CreateUserResponseDtoGroupsEnum>;
    /**
     * Passwords needs to contain at least 1 upper case letter, 1 lower case letter and 1 number or special character
     */
    password: string;
    /**
     * Unique username
     */
    username: string;
    /**
     * The ID of the newly created user
     */
    id: string;
    /**
     * Based on choosen user group, permissions will be added.
     */
    permissions: Array<CreateUserResponseDtoPermissionsEnum>;
}
export enum CreateUserResponseDtoGroupsEnum {
    ACCOUTING_ADMIN = 'ACCOUTING_ADMIN',
    ACCOUTING_READONLY = 'ACCOUTING_READONLY',
    ADMIN = 'ADMIN',
    DISPATCHER_ADMIN = 'DISPATCHER_ADMIN',
    DISPATCHER_READONLY = 'DISPATCHER_READONLY',
    DRIVER_READONLY = 'DRIVER_READONLY',
    OWNER = 'OWNER'
};
export enum CreateUserResponseDtoPermissionsEnum {
    CLIENT_MODULE_READ = 'CLIENT_MODULE_READ',
    CLIENT_MODULE_WRITE = 'CLIENT_MODULE_WRITE',
    COMPANY_MODULE_READ = 'COMPANY_MODULE_READ',
    COMPANY_MODULE_WRITE = 'COMPANY_MODULE_WRITE',
    COMPANY_USER_WRITE = 'COMPANY_USER_WRITE',
    DISPATCH_MODULE_READ = 'DISPATCH_MODULE_READ',
    DISPATCH_MODULE_WRITE = 'DISPATCH_MODULE_WRITE',
    EMPLOYEE_MODULE_READ = 'EMPLOYEE_MODULE_READ',
    EMPLOYEE_MODULE_WRITE = 'EMPLOYEE_MODULE_WRITE',
    INVOICE_MODULE_READ = 'INVOICE_MODULE_READ',
    INVOICE_MODULE_WRITE = 'INVOICE_MODULE_WRITE',
    LOAD_MODULE_READ = 'LOAD_MODULE_READ',
    LOAD_MODULE_WRITE = 'LOAD_MODULE_WRITE',
    USER_MODULE_READ = 'USER_MODULE_READ',
    USER_MODULE_WRITE = 'USER_MODULE_WRITE',
    VEHICLE_MAINTENANCE_MODULE_READ = 'VEHICLE_MAINTENANCE_MODULE_READ',
    VEHICLE_MAINTENANCE_MODULE_WRITE = 'VEHICLE_MAINTENANCE_MODULE_WRITE',
    VEHICLE_TRUCK_TRAILER_MODULE_READ = 'VEHICLE_TRUCK_TRAILER_MODULE_READ',
    VEHICLE_TRUCK_TRAILER_MODULE_WRITE = 'VEHICLE_TRUCK_TRAILER_MODULE_WRITE'
};



