/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserCreationDataDto } from './userCreationDataDto';


export interface CreateEmployeeResponseDto { 
    /**
     * If true, a user account will be created for the employee.
     */
    create_user: boolean;
    driver_card_number?: object;
    driver_card_validation_period?: object;
    driver_licence_number?: object;
    driver_licence_validation_period?: object;
    first_name: string;
    last_name: string;
    oib?: object;
    phone_number?: object;
    type: CreateEmployeeResponseDtoTypeEnum;
    /**
     * User creation data - required when create_user is true
     */
    user_creation_data?: UserCreationDataDto;
    created_at?: string;
    id: string;
    updated_at?: string;
}
export enum CreateEmployeeResponseDtoTypeEnum {
    ACCOUNTANT = 'ACCOUNTANT',
    DISPATCHER = 'DISPATCHER',
    DRIVER = 'DRIVER',
    MECHANIC = 'MECHANIC',
    OWNER = 'OWNER'
};



