/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateCompanyPayloadDtoAddress } from './createCompanyPayloadDtoAddress';


export interface CreateClientResponseDto { 
    address: CreateCompanyPayloadDtoAddress;
    /**
     * denis.truhlaz@truhlaz-transport.com
     */
    email?: string | null;
    /**
     * invoice@truhlaz-transport.com
     */
    invoice_email?: string | null;
    /**
     * +3859878112
     */
    mobile_number?: string | null;
    /**
     * Deki Company d.o.o.
     */
    name: string;
    /**
     * HR45633632215
     */
    vat_number: string;
    /**
     * 08:45
     */
    working_hours_from?: string | null;
    /**
     * 20:45
     */
    working_hours_to?: string | null;
    /**
     * The unique identifier of the created client
     */
    id: string;
}

