/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateCompanyPayloadDtoInvoiceSettingsVatDescriptionInner { 
    /**
     * OSLOBOĐENO PLAĆANJA PDV-a, ČL. 44, ST 1 T.35 ZAKONA O PDV-u
     */
    description: string;
}

