/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateInvoicePayloadDtoInvoiceProductsInner { 
    description?: string | null;
    discount?: number | null;
    gross_price: number;
    index: number;
    name: string;
    net_price: number;
    quantity: number;
    tax_percentage?: number | null;
    unit?: CreateInvoicePayloadDtoInvoiceProductsInnerUnitEnum | null;
}
export enum CreateInvoicePayloadDtoInvoiceProductsInnerUnitEnum {
    d = 'd',
    h = 'h',
    km = 'km',
    kg = 'kg',
    l = 'l',
    m = 'm',
    mi = 'mi',
    mo = 'mo',
    other = 'other',
    pcs = 'pcs',
    lb = 'lb',
    m2 = 'm2',
    t = 't',
    y = 'y'
};



