/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateUserPayloadDto { 
    /**
     * Assign unique email address
     */
    email: string;
    /**
     * Assign the user group or groupes you want the new user to have.
     */
    groups: Array<CreateUserPayloadDtoGroupsEnum>;
    /**
     * Passwords needs to contain at least 1 upper case letter, 1 lower case letter and 1 number or special character
     */
    password: string;
    /**
     * Unique username
     */
    username: string;
}
export enum CreateUserPayloadDtoGroupsEnum {
    ACCOUTING_ADMIN = 'ACCOUTING_ADMIN',
    ACCOUTING_READONLY = 'ACCOUTING_READONLY',
    ADMIN = 'ADMIN',
    DISPATCHER_ADMIN = 'DISPATCHER_ADMIN',
    DISPATCHER_READONLY = 'DISPATCHER_READONLY',
    DRIVER_READONLY = 'DRIVER_READONLY',
    OWNER = 'OWNER'
};



