/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateCompanyPayloadDtoAddress } from './createCompanyPayloadDtoAddress';


export interface CreateLoadPayloadDtoStopsInner { 
    /**
     * Driver must have 24 belts.
     */
    additional_requirement?: string | null;
    address: CreateCompanyPayloadDtoAddress;
    date: string;
    index: number;
    /**
     * AK423S423
     */
    loading_order_number?: string | null;
    /**
     * LOADING
     */
    type: CreateLoadPayloadDtoStopsInnerTypeEnum;
    /**
     * 08:45
     */
    working_hours_from?: string | null;
    /**
     * 20:45
     */
    working_hours_to?: string | null;
}
export enum CreateLoadPayloadDtoStopsInnerTypeEnum {
    LOADING = 'LOADING',
    UNLOADING = 'UNLOADING'
};



