/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateEmployeeResponseDto } from './createEmployeeResponseDto';
import { CreateTruckResponseDto } from './createTruckResponseDto';
import { CreateTrailerResponseDto } from './createTrailerResponseDto';
import { CreateUserResponseDto } from './createUserResponseDto';


export interface GetDispatchResponseDto { 
    employee: CreateEmployeeResponseDto;
    /**
     * The unique identifier
     */
    id: string;
    trailer: CreateTrailerResponseDto;
    truck: CreateTruckResponseDto;
    user: CreateUserResponseDto;
}

