/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetLoadsGroupedResponseDtoLoadsInner } from './getLoadsGroupedResponseDtoLoadsInner';
import { GetLoadsGroupedResponseDtoDispatch } from './getLoadsGroupedResponseDtoDispatch';


export interface GetLoadsGroupedResponseDto { 
    dispatch: GetLoadsGroupedResponseDtoDispatch;
    loads: Array<GetLoadsGroupedResponseDtoLoadsInner>;
}

