/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateLoadPayloadDtoStopsInner } from './createLoadPayloadDtoStopsInner';
import { CreateLoadPayloadDtoAdditionalCostsInner } from './createLoadPayloadDtoAdditionalCostsInner';
import { GetLoadsGroupedResponseDtoDispatch } from './getLoadsGroupedResponseDtoDispatch';
import { GetLoadsResponseDtoClient } from './getLoadsResponseDtoClient';


export interface GetLoadsResponseDto { 
    additional_costs?: Array<CreateLoadPayloadDtoAdditionalCostsInner> | null;
    create_invoice?: boolean;
    has_additional_costs?: boolean;
    invoice_first_number?: string;
    message_for_driver?: string | null;
    payment_date?: string | null;
    price?: number | null;
    /**
     * UNASSIGNED
     */
    status?: GetLoadsResponseDtoStatusEnum;
    stops: Array<CreateLoadPayloadDtoStopsInner>;
    client: GetLoadsResponseDtoClient;
    dispatch: GetLoadsGroupedResponseDtoDispatch;
    /**
     * This is the end date(highest) date from load stops and it will be automatically populated
     */
    stop_end_date: string;
    /**
     * This is the start date(lowest) date from load stops and it will be automatically populated
     */
    stop_start_date: string;
}
export enum GetLoadsResponseDtoStatusEnum {
    ASSIGNED = 'ASSIGNED',
    FINISHED = 'FINISHED',
    IN_PROGRESS = 'IN_PROGRESS',
    TEMPLATE = 'TEMPLATE',
    UNASSIGNED = 'UNASSIGNED'
};



