/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaginationResponseDtoMetadata } from './paginationResponseDtoMetadata';
import { CreateClientResponseDto } from './createClientResponseDto';


export interface PaginatedResponseOfCreateClientResponseDto { 
    metadata: PaginationResponseDtoMetadata;
    data?: Array<CreateClientResponseDto>;
}

