/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaginationResponseDtoMetadataPagination { 
    /**
     * Number of items per page, default is 10
     */
    limit?: number;
    /**
     * Page number, default is 1
     */
    page?: number;
    /**
     * Number of total items
     */
    totalCount: number;
    /**
     * Number of total pages
     */
    totalPages: number;
}

