/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetDispatchResponseDto } from './getDispatchResponseDto';
import { PaginationResponseDtoMetadata } from './paginationResponseDtoMetadata';


export interface PaginatedResponseOfGetDispatchResponseDto { 
    metadata: PaginationResponseDtoMetadata;
    data?: Array<GetDispatchResponseDto>;
}

