/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaginationResponseDtoMetadata } from './paginationResponseDtoMetadata';
import { GetInvoiceResponseDto } from './getInvoiceResponseDto';


export interface PaginatedResponseOfGetInvoiceResponseDto { 
    metadata: PaginationResponseDtoMetadata;
    data?: Array<GetInvoiceResponseDto>;
}

