/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetLoadsResponseDto } from './getLoadsResponseDto';
import { PaginationResponseDtoMetadata } from './paginationResponseDtoMetadata';


export interface PaginatedResponseOfGetLoadsResponseDto { 
    metadata: PaginationResponseDtoMetadata;
    data?: Array<GetLoadsResponseDto>;
}

