/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaginationResponseDtoMetadata } from './paginationResponseDtoMetadata';
import { CreateTruckResponseDto } from './createTruckResponseDto';


export interface PaginatedResponseOfCreateTruckResponseDto { 
    metadata: PaginationResponseDtoMetadata;
    data?: Array<CreateTruckResponseDto>;
}

