/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SignInResponseDtoUserCompany } from './signInResponseDtoUserCompany';
import { SignInResponseDtoUserEmployee } from './signInResponseDtoUserEmployee';


export interface SignInResponseDtoUser { 
    company?: SignInResponseDtoUserCompany;
    email: string;
    employee?: SignInResponseDtoUserEmployee;
    groups: Array<string>;
    id: string;
    username: string;
}

