/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateLoadPayloadDtoStopsInner } from './createLoadPayloadDtoStopsInner';
import { CreateLoadPayloadDtoAdditionalCostsInner } from './createLoadPayloadDtoAdditionalCostsInner';


export interface UpdateLoadPayloadDto { 
    additional_costs?: Array<CreateLoadPayloadDtoAdditionalCostsInner> | null;
    client_id?: string;
    create_invoice?: boolean;
    dispatch_id?: string;
    has_additional_costs?: boolean;
    invoice_first_number?: string;
    message_for_driver?: string | null;
    payment_date?: string | null;
    price?: number | null;
    /**
     * UNASSIGNED
     */
    status?: UpdateLoadPayloadDtoStatusEnum;
    stops: Array<CreateLoadPayloadDtoStopsInner>;
}
export enum UpdateLoadPayloadDtoStatusEnum {
    ASSIGNED = 'ASSIGNED',
    FINISHED = 'FINISHED',
    IN_PROGRESS = 'IN_PROGRESS',
    TEMPLATE = 'TEMPLATE',
    UNASSIGNED = 'UNASSIGNED'
};



