/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateInvoiceStatusDto { 
    /**
     * New status of the invoice
     */
    status: UpdateInvoiceStatusDtoStatusEnum;
}
export enum UpdateInvoiceStatusDtoStatusEnum {
    CANCELED = 'CANCELED',
    DRAFT = 'DRAFT',
    PAID = 'PAID',
    PENDING = 'PENDING',
    UNPAID = 'UNPAID'
};



