/**
 * Smart Fleet Management Swagger
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateInvoicePayloadDtoInvoiceProductsInner } from "./createInvoicePayloadDtoInvoiceProductsInner";

export interface UpdateInvoicePayloadDto {
  additional_information?: string | null;
  client_id?: string;
  /**
   * Currency of the invoice.
   */
  currency?: UpdateInvoicePayloadDtoCurrencyEnum | null;
  description?: string | null;
  invoice_first_number?: string | null;
  /**
   * Payment due invoice date.
   */
  invoice_payment_due_date?: string;
  invoice_products: Array<CreateInvoicePayloadDtoInvoiceProductsInner>;
  /**
   * List of load IDs to associate with the invoice.
   */
  load_id?: Array<string> | null;
  /**
   * PENDING
   */
  status?: UpdateInvoicePayloadDtoStatusEnum | null;
  total_discount_percentage?: number | null;
  total_price_after_vat?: number;
  total_price_before_vat?: number;
  /**
   * Description for VAT exemption, if applicable.
   */
  vat_description?: string | null;
  vat_value?: number | null;
}
export enum UpdateInvoicePayloadDtoCurrencyEnum {
  BAM = "BAM",
  CHF = "CHF",
  EUR = "EUR",
  GBP = "GBP",
  HRK = "HRK",
  PLN = "PLN",
  RSD = "RSD",
  USD = "USD",
}
export enum UpdateInvoicePayloadDtoStatusEnum {
  CANCELED = "CANCELED",
  DRAFT = "DRAFT",
  PAID = "PAID",
  PENDING = "PENDING",
  UNPAID = "UNPAID",
}
