/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateTruckPayloadDto { 
    /**
     * White
     */
    color?: string | null;
    /**
     * Employee ID
     */
    employee_id?: string | null;
    /**
     * DAF
     */
    make: UpdateTruckPayloadDtoMakeEnum;
    /**
     * 10/2019
     */
    manufacture_date?: string | null;
    /**
     * XF 530
     */
    model?: string | null;
    /**
     * 9/2025
     */
    registrated_until?: string | null;
    /**
     * DA0000TT
     */
    registration_plate: string;
    /**
     * STAKE_BODY
     */
    type?: UpdateTruckPayloadDtoTypeEnum | null;
    /**
     * XLTRE52455....
     */
    vin_number?: string | null;
}
export enum UpdateTruckPayloadDtoMakeEnum {
    Daewoo = 'Daewoo',
    DAF = 'DAF',
    Ford = 'Ford',
    Iveco = 'Iveco',
    Kamaz = 'Kamaz',
    Liebherr = 'Liebherr',
    Mack = 'Mack',
    Magirus_Deutz = 'Magirus Deutz',
    MAN = 'MAN',
    Meiller = 'Meiller',
    Mercedes_Benz = 'Mercedes-Benz',
    Mitsubishi = 'Mitsubishi',
    Nissan = 'Nissan',
    Opel = 'Opel',
    Other = 'Other',
    Peugeot = 'Peugeot',
    Renault = 'Renault',
    Scania = 'Scania',
    koda = 'Škoda',
    Steyr = 'Steyr',
    Tatra = 'Tatra',
    Toyota = 'Toyota',
    Unimog = 'Unimog',
    Volkswagen = 'Volkswagen',
    Volvo = 'Volvo'
};
export enum UpdateTruckPayloadDtoTypeEnum {
    BEVERAGES = 'BEVERAGES',
    BOX = 'BOX',
    BREAKDOWN = 'BREAKDOWN',
    CAR_CARRIER = 'CAR_CARRIER',
    CATTLE = 'CATTLE',
    CEMENT_MIXER = 'CEMENT_MIXER',
    CHASSIS = 'CHASSIS',
    CONCRETE_PUMP = 'CONCRETE_PUMP',
    DUMPER = 'DUMPER',
    GRAIN = 'GRAIN',
    HORSES = 'HORSES',
    HYDRAULIC_WORK_PLATFORM = 'HYDRAULIC_WORK_PLATFORM',
    MILK_TANK = 'MILK_TANK',
    MOUNTED_CRANE = 'MOUNTED_CRANE',
    OTHER = 'OTHER',
    REFRIGERATOR = 'REFRIGERATOR',
    REFUSE = 'REFUSE',
    ROLL_OFF_TIPPER = 'ROLL_OFF_TIPPER',
    STAKE_BODY = 'STAKE_BODY',
    STAKE_BODY_TARPAULIN = 'STAKE_BODY_TARPAULIN',
    STANDARD_TRACTOR = 'STANDARD_TRACTOR',
    SWEEPING_MACHINE = 'SWEEPING_MACHINE',
    TANK_BODY = 'TANK_BODY',
    TIMBER_CARRIER = 'TIMBER_CARRIER',
    TIPPER = 'TIPPER',
    VAN = 'VAN'
};



