/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateTrailerPayloadDto { 
    /**
     * Employee ID
     */
    employee_id?: string;
    /**
     * Schmitz
     */
    make?: UpdateTrailerPayloadDtoMakeEnum;
    /**
     * 10/2019
     */
    manufacture_date?: string | null;
    /**
     * Cargobull
     */
    model?: string | null;
    periodic_inspection?: string | null;
    /**
     * 9/2025
     */
    registrated_until?: string | null;
    /**
     * DA0000TT
     */
    registration_plate?: string;
    /**
     * LOW_LOADER
     */
    type?: UpdateTrailerPayloadDtoTypeEnum | null;
    /**
     * XLTRE52455....
     */
    vin_number?: string | null;
}
export enum UpdateTrailerPayloadDtoMakeEnum {
    Carnehl = 'Carnehl',
    Fliegl = 'Fliegl',
    Humbaur = 'Humbaur',
    Jotha = 'Jotha',
    Kssbohrer = 'Kässbohrer',
    Kempf = 'Kempf',
    Kgel = 'Kögel',
    Krone = 'Krone',
    Langendorf = 'Langendorf',
    MEGA = 'MEGA',
    Meiller = 'Meiller',
    Meusburger = 'Meusburger',
    Other = 'Other',
    Pezzaioli = 'Pezzaioli',
    Pongratz = 'Pongratz',
    Schmitz = 'Schmitz',
    Schwarzmller = 'Schwarzmüller',
    Wielton = 'Wielton',
    ZASAW = 'ZASŁAW'
};
export enum UpdateTrailerPayloadDtoTypeEnum {
    BEVERAGES = 'BEVERAGES',
    BOAT_TRAILER = 'BOAT_TRAILER',
    BOX = 'BOX',
    CAR_CARRIER = 'CAR_CARRIER',
    CATTLE = 'CATTLE',
    CHASSIS = 'CHASSIS',
    CONCRETE_PUMP = 'CONCRETE_PUMP',
    DEEP_FREEZE = 'DEEP_FREEZE',
    GLASS_TRANSPORT = 'GLASS_TRANSPORT',
    LONG_MATERIAL = 'LONG_MATERIAL',
    LOW_LOADER = 'LOW_LOADER',
    MILK_TANK = 'MILK_TANK',
    MOUNTED_CRANE = 'MOUNTED_CRANE',
    OTHER = 'OTHER',
    PLATFORM = 'PLATFORM',
    REFRIGERATOR = 'REFRIGERATOR',
    ROLL_OFF_TIPPER = 'ROLL_OFF_TIPPER',
    SILO = 'SILO',
    STAKE_BODY = 'STAKE_BODY',
    STAKE_BODY_TARPAULIN = 'STAKE_BODY_TARPAULIN',
    TANK_BODIES = 'TANK_BODIES',
    TIMBER_CARRIER = 'TIMBER_CARRIER',
    TIPPER = 'TIPPER',
    WALKING_FLOOR = 'WALKING_FLOOR'
};



