/**
 * Smart Fleet Management Swagger
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserCreationDataDto { 
    /**
     * Email address for the new user account
     */
    email: string;
    /**
     * User groups/permissions for the new user account
     */
    groups: Array<UserCreationDataDtoGroupsEnum>;
    /**
     * Password for the new user account (8-32 characters, must contain uppercase, lowercase, and number/special character)
     */
    password: string;
    /**
     * Username for the new user account
     */
    username: string;
}
export enum UserCreationDataDtoGroupsEnum {
    ACCOUTING_ADMIN = 'ACCOUTING_ADMIN',
    ACCOUTING_READONLY = 'ACCOUTING_READONLY',
    ADMIN = 'ADMIN',
    DISPATCHER_ADMIN = 'DISPATCHER_ADMIN',
    DISPATCHER_READONLY = 'DISPATCHER_READONLY',
    DRIVER_READONLY = 'DRIVER_READONLY',
    OWNER = 'OWNER'
};



