export const permission = {
  CLIENT_MODULE_READ: "CLIENT_MODULE_READ",
  CLIENT_MODULE_WRITE: "CLIENT_MODULE_WRITE",
  COMPANY_MODULE_READ: "COMPANY_MODULE_READ",
  COMPANY_MODULE_WRITE: "COMPANY_MODULE_WRITE",
  COMPANY_USER_WRITE: "COMPANY_USER_WRITE",
  DISPATCH_MODULE_READ: "DISPATCH_MODULE_READ",
  DISPATCH_MODULE_WRITE: "DISPATCH_MODULE_WRITE",
  EMPLOYEE_MODULE_READ: "EMPLOYEE_MODULE_READ",
  EMPLOYEE_MODULE_WRITE: "EMPLOYEE_MODULE_WRITE",
  INVOICE_MODULE_READ: "INVOICE_MODULE_READ",
  INVOICE_MODULE_WRITE: "INVOICE_MODULE_WRITE",
  LOAD_MODULE_READ: "LOAD_MODULE_READ",
  LOAD_MODULE_WRITE: "LOAD_MODULE_WRITE",
  USER_MODULE_READ: "USER_MODULE_READ",
  USER_MODULE_WRITE: "USER_MODULE_WRITE",
  VEHICLE_MAINTENANCE_MODULE_READ: "VEHICLE_MAINTENANCE_MODULE_READ",
  VEHICLE_MAINTENANCE_MODULE_WRITE: "VEHICLE_MAINTENANCE_MODULE_WRITE",
  VEHICLE_TRUCK_TRAILER_MODULE_READ: "VEHICLE_TRUCK_TRAILER_MODULE_READ",
  VEHICLE_TRUCK_TRAILER_MODULE_WRITE: "VEHICLE_TRUCK_TRAILER_MODULE_WRITE",
} as const;

export type Permission = (typeof permission)[keyof typeof permission];

export function isPermission(value: string | undefined): value is Permission {
  if (value) return (Object.values(permission) as string[]).includes(value);

  return false;
}

export const allPermissions: Permission[] = Object.values(permission);
