export enum Role {
  ACCOUNTANT = "ACCOUNTANT",
  ADMIN = "ADMIN",
  DISPATCHER = "DISPATCHER",
  DRIVER = "DRIVER",
  MACHINIST = "MACHINIST",
  MAINTENANCE = "MAINTENANCE",
  MANAGER = "MANAGER",
  OWNER = "OWNER",
  USER = "USER",
}
