export enum TrailerType {
  BEVERAGES = "BEVERAGES",
  BOAT_TRAILER = "BOAT_TRAILER",
  BOX = "BOX",
  CAR_CARRIER = "CAR_CARRIER",
  CATTLE = "CATTLE",
  CHASSIS = "CHASSIS",
  CONCRETE_PUMP = "CONCRETE_PUMP",
  DEEP_FREEZE = "DEEP_FREEZE",
  GLASS_TRANSPORT = "GLASS_TRANSPORT",
  LONG_MATERIAL = "LONG_MATERIAL",
  LOW_LOADER = "LOW_LOADER",
  MILK_TANK = "MILK_TANK",
  MOUNTED_CRANE = "MOUNTED_CRANE",
  OTHER = "OTHER",
  PLATFORM = "PLATFORM",
  REFRIGERATOR = "REFRIGERATOR",
  ROLL_OFF_TIPPER = "ROLL_OFF_TIPPER",
  SILO = "SILO",
  STAKE_BODY = "STAKE_BODY",
  STAKE_BODY_TARPAULIN = "STAKE_BODY_TARPAULIN",
  TANK_BODIES = "TANK_BODIES",
  TIMBER_CARRIER = "TIMBER_CARRIER",
  TIPPER = "TIPPER",
  WALKING_FLOOR = "WALKING_FLOOR",
}

// {
//   BEVERAGES = Za piće,
//   BOX = Sanduk,
//   CAR_CARRIER = Za vozila,
//   CATTLE = Stočarka,
//   CHASSIS = Šasija,
//   DEEP_FREEZE = Hladnjača - dupli režim,
//   MILK_TANK = Prehambrena cisterna,
//   LONG_MATERIAL = Produživa,
//   LOW_LOADER = Labudica,
//   PLATFORM = Platforma,
//   REFRIGERATOR = Hladnjača,
//   SILO = Silos cisterna,
//   STAKE_BODY = Sa stranicama,
//   STAKE_BODY_TARPAULIN = Cerada,
//   ROLL_OFF_TIPPER = Kontenjer,
//   TANK_BODIES = Cisterna,
//   TIMBER_CARRIER = Šumarska,
//   TIPPER = Kiper,
//   WALKING_FLOOR = Pomični pod,
//   CONCRETE_PUMP = Beton pumpa,
//   MOUNTED_CRANE = S kranom,
//   GLASS_TRANSPORT = Za stakla,
//   BOAT_TRAILER = Za brodove,
//   OTHER = ostalo
// }
