export enum TrailerMake {
  CARNEHL = "Carnehl",
  FLIEGL = "Fliegl",
  HUMBAUR = "Humbaur",
  JOTHA = "Jotha",
  KASSBOHRER = "Kässbohrer",
  KEMPF = "Kempf",
  KOGEL = "Kögel",
  KRONE = "Krone",
  LANGENDORF = "Langendorf",
  MEGA = "MEGA",
  MEILLER = "Meiller",
  MEUSBURGER = "Meusburger",
  OTHER = "Other",
  PEZZAIOLI = "Pezzaioli",
  PONGRATZ = "Pongratz",
  SCHMITZ = "Schmitz",
  SCHWARZMULLER = "Schwarzmüller",
  WIELTON = "Wielton",
  ZASLAW = "ZASŁAW",
}
