export enum TruckMake {
  DAEWOO = "Daewoo",
  DAF = "DAF",
  FORD = "Ford",
  IVECO = "Iveco",
  KAMAZ = "Kamaz",
  LIEBHERR = "Liebherr",
  MACK = "Mack",
  MAGIRUS_DEUTZ = "Magirus Deutz",
  MAN = "MAN",
  MEILLER = "Meiller",
  MERCEDES_BENZ = "Mercedes-Benz",
  MITSUBISHI = "Mitsubishi",
  NISSAN = "Nissan",
  OPEL = "Opel",
  OTHER = "Other",
  PEUGEOT = "Peugeot",
  RENAULT = "Renault",
  SCANIA = "Scania",
  SKODA = "Škoda",
  STEYR = "Steyr",
  TATRA = "Tatra",
  TOYOTA = "Toyota",
  UNIMOG = "Unimog",
  VOLKSWAGEN = "Volkswagen",
  VOLVO = "Volvo",
}
